# Generated by Django 6.0.5 on 2026-05-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='emoji',
            field=models.CharField(default='🔧', max_length=10),
        ),
    ]
