# Generated by Django 6.0.5 on 2026-06-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('major', 'Major'), ('minor', 'Minor'), ('', 'Standard')], default='', max_length=10),
        ),
    ]
