# Generated by Django 6.0.5 on 2026-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('research', 'Research / Paper'), ('tutorial', 'Tutorial'), ('note', 'Quick Note')], default='blog', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated read time in minutes (0 = auto)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_document',
            field=models.FileField(blank=True, help_text='Upload a .docx or .pdf — content will be extracted automatically.', null=True, upload_to='blog/documents/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
    ]
